version: "3"
services:
  redis:
    image: "redis:latest"
    expose:
      - 6379
  mongo:
    image: "mongo:latest"
    expose:
      - 27017
  mysql:
    image: "mysql:latest"
    expose:
      - 3306
  web:
    build: ../
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
      - mysql
    links:
      - redis
      - mongo
      - mysql
